### ISSUE TITLE
DONT DOWNLOAD

### ISSUE THREAD

**Issue by ghost** [ethernalsteve/DiscordTokenGrabber#17]
ITS DUALHOOKED GUYS DONT TRUST THIS I TESTED IT ON MY SECONDARY PC AND ON MY ALT DISCORD ACCOUNT AND IT STEALS THE TOKEN OF THE ACCOUNT. IM DEVELOPPER AND I KNOW WHERE IS REALLY DUALHOOKED. 

Check my profile to get cool stuff

**Comment by ghostof1337projects** [comment]
bro you didnt change the webhook

**Comment by MrShadowDev** [comment]
zorry

**Comment by MrShadowDev** [comment]
ok
